### ISSUE TITLE
 Slices of 1D arrays seem to be treated as 2D Arrays. 

### ISSUE THREAD

**Issue by wlruys** [bozhiyou/crosspy#3]
Slices of 1D arrays seem to be treated as 2D Arrays. 

## Error

```
Traceback (most recent call last):
  File "/work2/06081/wlruys/frontera/workspace/parla-experimental/minimal.py", line 38, in <module>
    main(T)
  File "/work2/06081/wlruys/frontera/workspace/parla-experimental/minimal.py", line 31, in main
    print("First Element: ", slicedA[0])
  File "/work2/06081/wlruys/frontera/mambaforge/envs/parla/lib/python3.10/site-packages/crosspy/core/ndarray.py", line 412, in __getitem__
    raise NotImplementedError("Only implemented for 1-D")
   
```

## Minimal Example

```python 

# from parla import Parla, spawn, TaskSpace
import argparse
import cupy as cp
import crosspy as xp

parser = argparse.ArgumentParser()
parser.add_argument("-dev_config", type=str, default="devices_sample.YAML")
parser.add_argument("-num_gpus", type=int, default=2)
args = parser.parse_args()

def main(T):

    # Per device size
    m = 3

    # Initilize a CrossPy Array
    cupy_list_A = []
    cupy_list_B = []
    for i in range(args.num_gpus):
        with cp.cuda.Device(0):
            random_array = cp.random.randint(0, 100, size=m)
            random_array = random_array.astype(cp.int32)

            cupy_list_A.append(random_array)
            cupy_list_B.append(cp.zeros(m, dtype=cp.int32))

    xA = xp.array(cupy_list_A, dim=0)
    xp.array(cupy_list_B, dim=0)

    slicedA = xA[slice(0, 1)]
    print("First Element: ", slicedA[0])
    print("First Element on CPU: ", slicedA[0].get(-1))



if __name__ == "__main__":
    T = None
    main(T)
```

## Full Example Script

```python

# from parla import Parla, spawn, TaskSpace
import argparse
import cupy as cp
import numpy as np
import crosspy as xp

parser = argparse.ArgumentParser()
parser.add_argument("-dev_config", type=str, default="devices_sample.YAML")
parser.add_argument("-num_gpus", type=int, default=2)
args = parser.parse_args()

np.random.seed(10)
cp.random.seed(10)

# TODO(wlr): Fuse this kernel
def partition_kernel(A, B, comp, pivot):
    comp[:] = (A < pivot)
    mid = comp.sum()
    B[:mid] = A[comp]
    B[mid:] = A[~comp]
    return mid


def partition(xA, xB, pivot):
    n_partitions = len(xA.values())
    mid = np.zeros(n_partitions+1, dtype=np.uint32)

    for i, (array_in, array_out) in enumerate(zip(xA.values(), xB.values())):
        with cp.cuda.Device(0):
            comp = cp.empty_like(array_in, dtype=cp.bool_)
            mid[i+1] = partition_kernel(array_in, array_out, comp, pivot)
    return mid


# TODO(wlr): Fuse this kernel, pack this better?
def scatter(splits, xA, xB):
    """
    :param xA, xB,  sliced crosspy arrays for the active element set
    :param splits, a host ndarray of how many left elements are in each partition 
    """

    n_partitions = len(xA.values())

    sizes = np.zeros(n_partitions+1, dtype=np.uint32)
    for i, array in enumerate(xB.values()):
        sizes[i+1] = len(array)
    
    size_prefix = np.cumsum(sizes)
    left_prefix = np.cumsum(splits)

    right_prefix = size_prefix - left_prefix
    local_split = np.sum(splits)

    right_prefix += local_split

    print("Size Prefix: ", size_prefix)
    print("Left Prefix: ", left_prefix)
    print("Right Prefix: ", right_prefix)

    for i in range(n_partitions):

        print(f"Performing left copy from Partition {i}: ", (left_prefix[i], left_prefix[i+1]), (size_prefix[i], size_prefix[i] + splits[i+1]))


        # Write left
        if splits[i+1] > 0:
            xA[left_prefix[i]:left_prefix[i+1]] = xB[size_prefix[i]:size_prefix[i]+splits[i+1]]


        print(f"Performing right copy from Partition {i}: ", (right_prefix[i], right_prefix[i+1]), (size_prefix[i]+splits[i+1], size_prefix[i+1]))
        # Write right
        if (sizes[i+1] - splits[i+1]) > 0:
            xA[right_prefix[i]:right_prefix[i+1]] = xB[size_prefix[i]+splits[i+1]:size_prefix[i+1]]

    return local_split

def quicksort(xA, xB, active_slice, T):

    print("----------------------")
    print("Starting Partition on Slice: ", active_slice)
    n_partitions = len(xA.values())
    print("CrossPy has n_partitions: ", n_partitions)

    active_A = xA[active_slice]
    active_B = xB[active_slice]

    pivot_idx = np.random.randint(0, len(active_A))

    print("Active partition has shape: ", active_A.shape)
    print("Active partition has len: ", len(active_A))

    print("The chosen pivot index is: ", pivot_idx)
    pivot = (int)(active_A[pivot_idx].to(-1))

    print("The chosen pivot is: ", pivot)

    # local partition
    print("Performing local partition...")
    splits = partition(active_A, active_B, pivot)
    print("Found the following splits: ", splits)

    # Scatter to other partitions
    print("Performing local scatter...")
    local_split = scatter(splits, active_A, active_B)


    #form slices to pass to children
    previous_start = active_slice.start 
    previous_end = active_slice.stop

    left_start = (int)(previous_start)
    left_end = (int)(previous_start + local_split)
    left_slice = slice(left_start, left_end)

    right_start = (int)(previous_start + local_split)
    right_end = (int)(previous_end)
    right_slice = slice(right_start, right_end)



    quicksort(xA, xB, left_slice, T)
    quicksort(xA, xB, right_slice, T)




def main(T):

    # Per device size
    m = 3

    # Initilize a CrossPy Array
    cupy_list_A = []
    cupy_list_B = []
    for i in range(args.num_gpus):
        with cp.cuda.Device(0):
            random_array = cp.random.randint(0, 100, size=m)
            random_array = random_array.astype(cp.int32)

            cupy_list_A.append(random_array)
            cupy_list_B.append(cp.zeros(m, dtype=cp.int32))

    xA = xp.array(cupy_list_A, dim=0)
    xB = xp.array(cupy_list_B, dim=0)

    print("Original Array: ", xA)
    quicksort(xA, xB, slice(0, len(xA)), T)

    print("Sorted: ", xA)


if __name__ == "__main__":
    T = None
    main(T)
    
   ```

**Comment by bozhiyou** [comment]
It's actually not treated as 2-D but scalar (0-D). Added support since version 0.0.0a3.dev7.

Minor: `slicedA[0].to(-1)` for movement, not `get`. Docs coming soon :)
